# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23ed6e752fec1a8d0dccdb949e5f7582250a7a94352aeb1febb80377dd413aca3ef563e72f36702ab7cf5b903040677e10bf7a95ac9dd3a29b5116e112f1e66a

test:
  secret_key_base: 6b9483652c84cfe45de5f99939af474f4c2da89c2238ad856fdaaced7db19c013f851cd5b50673d9e7ade740da206a69d4dba7a2b8b76c989fb53e6f049592f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
